"""initial core schema

Revision ID: 24a71e10e97c
Revises: 
Create Date: 2026-06-03 21:02:32.217153
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '24a71e10e97c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('pipeline_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('items_in', sa.Integer(), nullable=True),
    sa.Column('items_out', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('adapter_class', sa.String(), nullable=False),
    sa.Column('tier', sa.String(length=1), nullable=False),
    sa.Column('config_jsonb', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status', sa.String(), nullable=True),
    sa.Column('rate_limit_rpm', sa.Integer(), nullable=False),
    sa.CheckConstraint("tier in ('A','B','C')", name='ck_sources_tier'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('tools',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('canonical_url', sa.Text(), nullable=False),
    sa.Column('canonical_url_hash', sa.String(), nullable=False),
    sa.Column('one_liner', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('pricing_model', sa.String(), nullable=True),
    sa.Column('starting_price_usd_monthly', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('country_hq', sa.String(length=2), nullable=True),
    sa.Column('launch_date', sa.DateTime(), nullable=True),
    sa.Column('is_open_source', sa.Boolean(), nullable=False),
    sa.Column('github_url', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('quality_score', sa.Integer(), nullable=True),
    sa.Column('is_duplicate_of_id', sa.Uuid(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['is_duplicate_of_id'], ['tools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_url_hash', name='uq_tools_canonical_url_hash')
    )
    with op.batch_alter_table('tools', schema=None) as batch_op:
        batch_op.create_index('ix_tools_first_seen', ['first_seen_at'], unique=False)
        batch_op.create_index('ix_tools_quality', ['quality_score'], unique=False)

    op.create_table('candidate_urls',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('url_hash', sa.String(), nullable=False),
    sa.Column('raw_title', sa.Text(), nullable=True),
    sa.Column('raw_excerpt', sa.Text(), nullable=True),
    sa.Column('signal_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url_hash', name='uq_candidate_urls_url_hash')
    )
    with op.batch_alter_table('candidate_urls', schema=None) as batch_op:
        batch_op.create_index('ix_candidate_urls_status_discovered', ['status', 'discovered_at'], unique=False)

    op.create_table('tool_categories',
    sa.Column('tool_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tool_id', 'category_id')
    )
    op.create_table('tool_evidence',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tool_id', sa.Uuid(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=False),
    sa.Column('field_value', sa.Text(), nullable=False),
    sa.Column('evidence_quote', sa.Text(), nullable=False),
    sa.Column('evidence_url', sa.Text(), nullable=False),
    sa.Column('extracted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_pages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('candidate_url_id', sa.Uuid(), nullable=False),
    sa.Column('clean_text', sa.Text(), nullable=True),
    sa.Column('html_hash', sa.String(), nullable=True),
    sa.Column('screenshot_url', sa.Text(), nullable=True),
    sa.Column('fetcher_used', sa.String(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_url_id'], ['candidate_urls.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_url_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('raw_pages')
    op.drop_table('tool_evidence')
    op.drop_table('tool_categories')
    with op.batch_alter_table('candidate_urls', schema=None) as batch_op:
        batch_op.drop_index('ix_candidate_urls_status_discovered')

    op.drop_table('candidate_urls')
    with op.batch_alter_table('tools', schema=None) as batch_op:
        batch_op.drop_index('ix_tools_quality')
        batch_op.drop_index('ix_tools_first_seen')

    op.drop_table('tools')
    op.drop_table('sources')
    op.drop_table('pipeline_runs')
    op.drop_table('categories')
    # ### end Alembic commands ###
