"""add curator fields to tools

Revision ID: b2ca612e0f01
Revises: 24a71e10e97c
Create Date: 2026-06-03 22:42:17.347774
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2ca612e0f01'
down_revision: Union[str, None] = '24a71e10e97c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tools', schema=None) as batch_op:
        batch_op.add_column(sa.Column('decision_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('curated_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tools', schema=None) as batch_op:
        batch_op.drop_column('curated_at')
        batch_op.drop_column('decision_reason')

    # ### end Alembic commands ###
